- README.md
- src/rocks_init.cpp
- src/rocks_server_status.cpp
- src/rocks_server_status.h
This also changes disk format, since storage engine names are case
sensitive. You'll need to reload your database with
mongodump/mongorestore.
> Change every occurrence of RocksDB with rocksdb

- src/rocks_recovery_unit.h
- src/rocks_snapshot_manager.cpp
- src/rocks_snapshot_manager.h
Problem description:
The crash was caused by dangling pointer to RocksRecoveryUnit stored in the instance of RocksSnapshotManager::SnapshotHolder class.
Crash scenario:
- execute administrative 'makeSnapshot' command. This will create instance of RocksSnapshotManager::SnapshotHolder which is stored in RocksSnapshotManager's snapshots map.
- SnapshotHolder has raw pointer to RocksRecoveryUnit instance which is destroyed at the end of 'makeSnapshot' command handler
- destructor of SnapshotHolder is called on shutdown when snapshot maps are cleared in RocksSnapshotManager::dropAllSnapshots
- destructor of SnapshotHolder tries to release snapshot using stored pointer to RocksRecoveryUnit instance which was destroyed earlier
Fix description:
Instead of storing RocksRecoveryUnit pointer in …
> SERVER-21311 fixing crash on shutdown in RocksRecoveryUnit::dbReleaseSnapshot

- src/rocks_record_store.cpp
- src/rocks_record_store.h
- src/rocks_record_store_test.cpp
this is mongo-rocks analog of https://github.com/mongodb/mongo/commit/0e4d706953cd4db25fc9ffa4abf106541157f971
> SERVER-21645 RocksRecordStore::temp_cappedTruncateAfter should set _oplog_highestSeen

- SConscript
Hello,
I broke the rocksdb build in commit dafe72f68 on mongodb/master. Adding this libdep edge should fix it.
Best,
Adam
> SERVER-22245 add missing libdep to storage_rocks_engine_test

- src/rocks_engine.cpp
- src/rocks_global_options.cpp
- src/rocks_global_options.h
- src/rocks_index.cpp
- src/rocks_index.h
Replace `Delete` with `SingleDelete` in `unindex` method of standard index.
This also required adding a check to disallow multiple consecutive `SingleDelete` calls under some circumstances.
Add config option `rocksdb.storage.singleDeleteIndex` to enable `SingleDelete` behavior.
This is the replacement for https://github.com/mongodb-partners/mongo-rocks/pull/16
> Use SingleDelete for standard index (take 2, with config option)

- SConscript
- src/rocks_engine.cpp
- src/rocks_global_options.cpp
This patch should be safe to merge after MongoDB bug SERVER-24588 (https://jira.mongodb.org/browse/SERVER-24588) will be fixed
> PSMDB-72 LZ4 compression for MongoRocks is not available

- src/rocks_index.cpp
The issue was fixed in RocksStandardIndex::unindex() by Denis Protivennskiy (see commit 2ce7891).
But the same issue exists in RocksUniqueIndex::unindex(). This patch is to fix it too.
This patch should be cherry-picked to v3.2 branch.
> PSMDB-81 no need to unindex oversized keys

- src/rocks_engine.cpp
- src/rocks_engine.h
(Fixed version of #37)
We recently changed KVEngine::getRecordStore to return a unique pointer rather than a raw pointer to fix a memory leak, which makes the following changes necessary.
> Change `RocksEngine::getRecordStore` to return a unique pointer (fixed)

- src/rocks_engine.cpp
- src/rocks_record_store.cpp
- src/rocks_record_store.h
- src/rocks_record_store_mock.cpp
- src/rocks_record_store_test.cpp
Includes oplog_highestSeen (from https://github.com/mongodb-partners/mongo-rocks/pull/13) and `waitForAllEarlierOplogWritesToBeVisible` API change.
> Fix 3.2.11 build

- src/rocks_engine.cpp
- src/rocks_index.cpp
- src/rocks_index.h
- src/rocks_index_test.cpp
Allows to pass noPassthrough/index_version_v2.js test for MongoRocks.
(cherry picked from commit 2709c2e2496acaefb6bbcda6cb44ad4405752185)
> SERVER-25156 Add support for building v=2 indexes

- SConscript
(cherry picked from commit 4d6676d9d0bcfcc947d8ee963932e521a66005df)
(cherry picked from commit 55dc02940225ba1cd82129fee71a3448d6bba896)
> Fix unittests target when built with --ssl option

- src/rocks_init.cpp
- src/rocks_parameters.cpp
- src/rocks_parameters.h
Use can now use:
```db.runCommand({ setParameter: 1, rocksdbOptions: "level0_stop_writes_trigger=90; level0_slowdown_writes_trigger=90" })```
to update parameters dynamically
Or:
```
db.runCommand({ getParameter: 1, "rocksdbOptions": 1})
```
To get parameters values
Note that only from RocksDB 4.13.0 and up if you run set and then get you will get the updated parameters and not the ones from boot.
> Added option to dynamically change RocksDB options using setParameter

- src/rocks_engine.cpp
- src/rocks_engine.h
- src/rocks_parameters.cpp
- src/rocks_parameters.h
- src/rocks_server_status.cpp
The concept is copied from WT:
https://github.com/mongodb/mongo/blob/master/src/mongo/db/storage/wiredtiger/wiredtiger_kv_engine.cpp#L290
Currently, there is no protection in MongoRocks from multiple queries ( > 1000 or whatever).
What could happen (and has happened to us in some cases) is that in a flood of queries, every query (that's how mongo works) will open a thread trying to read. That could stack up to thousands of threads, causing more context switches than actual work, which causes the database to basically halt.
In WT they are protecting it by using Mongo's global lock, that creates a queue of readers/writers whenever such a flood occurs, instead of letting everyone in.
The parameter is configurable in runtime and also monitorable using serverStatus()
> Added concurrency limit to RocksDB to avoid DoS from queries

- src/rocks_record_store.cpp
- src/rocks_record_store.h
Currently, oplog compaction is only time based (const of 30 mins).
In write intensive environments, even setting it to 1 minute may sometimes not be enough.
I added another threshold which is the deleted key count for compaction.
During my tests, with a pretty decent insert rate (~60-80K IPS, 400B docs) this is performing a lot better than previously without all the tombstones that were there without the patch.
I also improved the log, so that you will know if time or deleted # was the compaction trigger.
I set the threshold constant to 500K records. I did some tests and this seems to be a good number. If you have any other tests that you would like to run in order to validate, let me know.
> V3.2 add deleted count compaction threshold

- src/rocks_record_store_mongod.cpp
The class has been removed and its functionality is now covered by GlobalLock.
> SERVER-22541: Remove ScopedTransaction. 

- src/rocks_engine.cpp
- src/rocks_index.cpp
- src/rocks_index.h
- src/rocks_index_test.cpp
* Add index and collection name in dup key error message
* Pass needed parameters by value in UniqueBulkBuilder and RocksUniqueIndex
Conflicts:
src/rocks_engine.cpp
src/rocks_index.cpp
src/rocks_index.h
> PSMDB-126 Add index and collection name in dup key error message

- src/rocks_engine.cpp
- src/rocks_record_store.cpp
This is mongo-rocks version of commits:
https://github.com/mongodb/mongo/commit/63d1f4c049587e7923a1154fc31f29bc190316df
https://github.com/mongodb/mongo/commit/8056164a27fcaa1429744f9f2ff039a3d8c39b6f
> SERVER-27727 Hide idle threads in hang analyzer (mongo-rocks)

- src/rocks_recovery_unit.cpp
RocksDB commit https://github.com/facebook/rocksdb/commit/7f6c02dda16471c2ed3318e9e7156f2b8d13bf46 hides the perf_context global variable. This fixes the build.
> Fix the build with RocksDB master

- src/rocks_compaction_scheduler.cpp
- src/rocks_compaction_scheduler.h
- src/rocks_engine.cpp
- src/rocks_engine.h
- src/rocks_parameters.cpp
- src/rocks_record_store.cpp
- src/rocks_record_store.h
- src/rocks_record_store_test.cpp
The change introduces background compaction thread with `DeleteFilesInRange` and bottommost level compaction enabled.
This is the first part of the changes which will be followed by more code improvements where compaction-related code is completely moved to the `RocksCompactionScheduler`.
> PSMDB-127 Implementation of compaction on the background thread

- src/rocks_compaction_scheduler.cpp
- src/rocks_compaction_scheduler.h
- src/rocks_engine.cpp
- src/rocks_engine.h
- src/rocks_parameters.cpp
- src/rocks_record_store.cpp
- src/rocks_record_store.h
- src/rocks_record_store_test.cpp
The change introduces background compaction thread with `DeleteFilesInRange` and bottommost level compaction enabled.
This is the first part of the changes which will be followed by more code improvements where compaction-related code is completely moved to the `RocksCompactionScheduler`.
> PSMDB-127 Implementation of compaction on the background thread (v3.2)

- src/rocks_recovery_unit.cpp
this check ``` _writeBatch.GetWriteBatch()->Count() > 0 ``` makes ``` _deltaCounters ``` lost
flowing code doesn't work .
```
void RocksRecordStore::updateStats(OperationContext* txn, long long numRecordsInc, long long dataSizeInc) {
WriteUnitOfWork wuow(txn);
auto ru = RocksRecoveryUnit::getRocksRecoveryUnit(txn);
ru->incrementCounter(_numRecordsKey, &_numRecords, numRecordsInc);
ru->incrementCounter(_dataSizeKey, &_dataSize, dataSizeInc);
wuow.commit();
}
```
> Fix RocksRecoveryUnit commit issus

- src/rocks_record_store.cpp
MergingIterator::status() is unfriendly to performance , we should not call it frequently .
on bulkload mode , we may have many many lv0 sst , it will make Cursor stuck .
https://github.com/facebook/rocksdb/blob/9b11d4345a0f01fc3de756e01460bf1b0446f326/table/merging_iterator.cc#L271
> Fix Cursor performance issus

- src/rocks_record_store.h
@igorcanadi, I believe RocksRecordStore cursor retrieves its documents in RecordId order, so `isInRecordIdOrder()` should be true?
> SERVER-30313 RocksRecordStore::isInRecordIdOrder() should return true

- src/rocks_record_store.cpp
This is a fix for the issue https://github.com/mongodb-partners/mongo-rocks/issues/108
> fix random CheckReplOplog failures in 'passthough' test suites

- src/rocks_snapshot_manager.cpp
this is mongo-rocks port of commit 512ae2b48672
it fixes invariant failures in 3.6.0-rc0 and newer
> SERVER-19213  clean up invariants around snapshot creation

- src/rocks_record_store_mongod.cpp
In queryable backup mode the oplog truncation would never occur. Hence oplog sampling
is disabled this mode.
> SERVER-23935 Disable oplog sampling in queryable backup mode

- src/rocks_server_status.cpp
This has already been in master: https://github.com/mongodb-partners/mongo-rocks/pull/110
But it was also ported back in 3.4.9
> SERVER-30790: Have RocksServerStatusSection take a Global IS lock

- src/rocks_engine.cpp
- src/rocks_engine.h
It may happen that ident has already been dropped and this info
persisted separately, but upper layer metadata didn't persist because
of system crash on standalone instance with default acknowledgement
behavior.
> PSMDB-164 Ignore missing ident in dropIdent

- src/rocks_compaction_scheduler.cpp
- src/rocks_compaction_scheduler.h
- src/rocks_engine.cpp
This closes very serious data integrity issue.
It is hard to ensure but it probably fixes issue #79 and issue #80 .
Should be ported to all version branches.
> PSMDB-191 take into account dropped prefixes when calculating _maxPrefix

- src/rocks_engine.cpp
By YCSB benchmarking, it's confirmed that loading 10 000 000 records into mongorocks 4.0 finally succeeds. `CleanCommittedKeys` thread seems to be working well, and memory is not overwhelmed with excessive committed keys any more.
> Advance oldestTimestamp when setStableTimestamp called (#152)

- src/rocks_compaction_scheduler.cpp
- src/rocks_record_store.cpp
when running the mongos js test suite, replica_sets_ill_secondaries_jscore_passthrough, there is probability
memory issue which lead mongod crash.
```c++
uint32_t RocksCompactionScheduler::loadDroppedPrefixes(rocksdb::Iterator* iter,
std::vector<rocksdb::ColumnFamilyHandle*> cfs) {
invariant(iter);
const uint32_t rocksdbSkippedDeletionsInitial =
(uint32_t)get_internal_delete_skipped_count();
int dropped_count = 0;
uint32_t int_prefix = 0;
for (iter->Seek(kDroppedPrefix); iter->Valid() && iter->key().starts_with(kDroppedPrefix);
iter->Next()) {
invariantRocksOK(iter->status());
rocksdb::Slice prefix(iter->key());
prefix.remove_prefix(kDroppedPrefix.size());
// let's instruct the compaction scheduler to compact dropped prefix
++dropped_count;
bool ok = extractPrefix(prefix, &int_prefix); …
```
> fix memory issue and build error

- src/rocks_compaction_scheduler.cpp
- src/totdb/totransaction_db.h
TOTransactionDB enables timestamp, so when oplog compaction filter, you need to delete timestamp from user key
> Remove Timestamp info from user key in oplog compaction filter

- src/rocks_record_store.cpp
- src/rocks_record_store.h
Because the latest version of rocksdb supports timestamp,
the resulting f.largestkey contains timestamp information.
For oplog reclaim operation, we only need to compare the userkey,
and we don't need the timestamp inside the rocksdb key,
so we should delete it.
> remove f.largestkey timestamp

- src/rocks_engine.cpp
- src/rocks_engine.h
- src/rocks_record_store.cpp
- src/totdb/totransaction_db.h
- src/totdb/totransaction_db_impl.cpp
The rollback logic at the mongo-server level calls the rtt(rollback to timestamp) function of the storage engine layer.
This requires user data rollback, but oplog cannot be rolled back. However, at present, the rollback operation of rocksdb is done at the opendb time,
and no parameters can be set to decide which cf needs to be rolled back and which cf cannot be rolled back.
Inside rocksdb, it is only based on the timestamp turned on at the cf time to decide whether to roll back.
Therefore, in order to meet the oplog non-roll policy required by the upper level of mongo,
we temporarily set oplog cf not support ts to make rocksdb skip the rollback behavior of oplog cf.
> use fakeCompator to skip oplog cf trim operation
